server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    drive-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASS:123456}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander
  version: 1.0
  termsOfService: http://swagger.io/terms
  url: http://springdoc.org